[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 200

solc_version = "0.8.20"
fs_permissions =[{ access ="read", path ="./"}]

[etherscan]
polygon-amoy = { key ="${AMOY_API_KEY}",url ="https://api-amoy.polygonscan.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
